# Generated by Django 4.0.5 on 2023-08-18 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('단비', '단비'), ('다래', '다래'), ('블라블라', '블라블라'), ('철로', '철로'), ('땅이', '땅이'), ('해태', '해태'), ('수피', '수피')], max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('is_complete', models.BooleanField(default=False)),
                ('complete_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('단비', '단비'), ('다래', '다래'), ('블라블라', '블라블라'), ('철로', '철로'), ('땅이', '땅이'), ('해태', '해태'), ('수피', '수피')], max_length=10)),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
    ]
