# Generated by Django 4.2.4 on 2023-08-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtask",
            name="completed_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="complete_date",
            field=models.DateTimeField(null=True),
        ),
    ]
