# Generated by Django 4.2.4 on 2023-08-19 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_alter_subtask_completed_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task", old_name="complete_date", new_name="completed_date",
        ),
    ]
