# Generated by Django 4.2.4 on 2023-08-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=20, unique=True, verbose_name="사용자 계정"),
                ),
                ("password", models.CharField(max_length=128, verbose_name="비밀번호")),
                (
                    "team",
                    models.CharField(
                        choices=[
                            ("단비", "단비"),
                            ("다래", "다래"),
                            ("블라블라", "블라블라"),
                            ("철로", "철로"),
                            ("땅이", "땅이"),
                            ("해태", "해태"),
                            ("수피", "수피"),
                        ],
                        max_length=10,
                        verbose_name="팀",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={"abstract": False,},
        ),
    ]
